ControlFocus("Open","","Edit1")
Sleep(2000)
ControlSetText("Open","","Edit1","C:\Users\DELL\Desktop\selenium_logo_square_green.png")
Sleep(2000)
ControlFocus("Open","","Button1")
Sleep(2000)
ControlClick("Open","","Button1")
